export const mockContent = [
  {
    id: '1',
    title: 'The Last Expedition',
    platform: 'Netflix',
    image: 'https://images.unsplash.com/photo-1739891251370-05b62a54697b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhY3Rpb24lMjBtb3ZpZSUyMHBvc3RlcnxlbnwxfHx8fDE3NjAwNzA2NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 8.5,
    year: 2024,
    type: 'film' as const,
    description: 'En episk actionfilm om en gruppe utforskere som må redde verden.',
    duration: 142,
    mood: ['action', 'kos'],
    genres: ['thriller', 'scifi'],
    language: 'engelsk',
    intensity: 'intense',
    familyFriendly: false
  },
  {
    id: '2',
    title: 'Planet Earth III',
    platform: 'Viaplay',
    image: 'https://images.unsplash.com/photo-1603016129004-c7539f86b53f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjBkb2N1bWVudGFyeXxlbnwxfHx8fDE3NjAwNDk0Njh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 9.2,
    year: 2024,
    type: 'serie' as const,
    description: 'Fantastisk naturdokumentar som viser verdens mest utrolige dyr og landskap.',
    duration: 52,
    mood: ['laring', 'kos'],
    genres: ['dokumentar'],
    language: 'engelsk',
    intensity: 'lett',
    familyFriendly: true
  },
  {
    id: '3',
    title: 'Comedy Central Presents',
    platform: 'HBO Max',
    image: 'https://images.unsplash.com/photo-1758726942669-92f7e499018c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21lZHklMjBzaG93JTIwdGhlYXRlcnxlbnwxfHx8fDE3NjAwNjEzNTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 7.8,
    year: 2024,
    type: 'serie' as const,
    description: 'De beste standupkomikerne fra hele verden leverer lattergaranti.',
    duration: 30,
    mood: ['latter', 'kos'],
    genres: ['komedie'],
    language: 'engelsk',
    intensity: 'lett',
    familyFriendly: true
  },
  {
    id: '4',
    title: 'Love in Paris',
    platform: 'Disney+',
    image: 'https://images.unsplash.com/photo-1658851866325-49fb8b7fbcb2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb21hbnRpYyUyMGNvdXBsZSUyMHN1bnNldHxlbnwxfHx8fDE3NjAwODE4MTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 7.5,
    year: 2023,
    type: 'film' as const,
    description: 'En romantisk komedie om to mennesker som møtes i Paris.',
    duration: 98,
    mood: ['kos', 'latter'],
    genres: ['romantikk', 'komedie'],
    language: 'engelsk',
    intensity: 'lett',
    familyFriendly: true
  },
  {
    id: '5',
    title: 'Future World',
    platform: 'Discovery+',
    image: 'https://images.unsplash.com/photo-1603459404736-ee279d02d26c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY2llbmNlJTIwZmljdGlvbiUyMGZ1dHVyZXxlbnwxfHx8fDE3NjAxMjIwNjJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 8.9,
    year: 2024,
    type: 'serie' as const,
    description: 'En sci-fi thriller som utforsker fremtidens teknologi og menneskeheten.',
    duration: 45,
    mood: ['action', 'laring'],
    genres: ['scifi', 'thriller'],
    language: 'engelsk',
    intensity: 'intense',
    familyFriendly: false
  },
  {
    id: '6',
    title: 'Dark Secrets',
    platform: 'Netflix',
    image: 'https://images.unsplash.com/photo-1647264157150-491bfd016aa1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aHJpbGxlciUyMGRhcmslMjBteXN0ZXJ5fGVufDF8fHx8MTc2MDEyMjA2M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 8.2,
    year: 2024,
    type: 'serie' as const,
    description: 'En spennende thriller om mysterier som avdekkes i en liten by.',
    duration: 48,
    mood: ['action', 'kos'],
    genres: ['thriller', 'drama'],
    language: 'engelsk',
    intensity: 'medium',
    familyFriendly: false
  },
  {
    id: '7',
    title: 'Family Adventure',
    platform: 'Disney+',
    image: 'https://images.unsplash.com/photo-1628676306092-1238ef1dc851?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYW1pbHklMjBjaGlsZHJlbiUyMGhhcHB5fGVufDF8fHx8MTc2MDEyMjA2M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 7.0,
    year: 2024,
    type: 'film' as const,
    description: 'En morsom familiefilm om eventyr og vennskap.',
    duration: 95,
    mood: ['kos', 'latter'],
    genres: ['komedie'],
    language: 'norsk',
    intensity: 'lett',
    familyFriendly: true
  },
  {
    id: '8',
    title: 'Noir Detective',
    platform: 'HBO Max',
    image: 'https://images.unsplash.com/photo-1695037642839-ad92d088ce98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkcmFtYSUyMGZpbG0lMjBub2lyfGVufDF8fHx8MTc2MDEwNDk0OHww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 8.7,
    year: 2023,
    type: 'serie' as const,
    description: 'En dramatisk detektivserie i klassisk noir-stil.',
    duration: 55,
    mood: ['action', 'laring'],
    genres: ['drama', 'thriller'],
    language: 'engelsk',
    intensity: 'medium',
    familyFriendly: false
  },
  {
    id: '9',
    title: 'Cooking Masters',
    platform: 'TV 2 Play',
    image: 'https://images.unsplash.com/photo-1603016129004-c7539f86b53f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjBkb2N1bWVudGFyeXxlbnwxfHx8fDE3NjAwNDk0Njh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 7.3,
    year: 2024,
    type: 'serie' as const,
    description: 'Konkurranseprogrammet hvor de beste kokkene møtes.',
    duration: 42,
    mood: ['laring', 'kos'],
    genres: ['dokumentar'],
    language: 'norsk',
    intensity: 'lett',
    familyFriendly: true
  },
  {
    id: '10',
    title: 'Space Odyssey 2025',
    platform: 'Viaplay',
    image: 'https://images.unsplash.com/photo-1603459404736-ee279d02d26c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY2llbmNlJTIwZmljdGlvbiUyMGZ1dHVyZXxlbnwxfHx8fDE3NjAxMjIwNjJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 8.8,
    year: 2024,
    type: 'film' as const,
    description: 'En storslått sci-fi film om romfart og menneskelig utforskning.',
    duration: 165,
    mood: ['action', 'laring'],
    genres: ['scifi'],
    language: 'engelsk',
    intensity: 'intense',
    familyFriendly: false
  },
  {
    id: '11',
    title: 'Stand Up Night',
    platform: 'Netflix',
    image: 'https://images.unsplash.com/photo-1758726942669-92f7e499018c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21lZHklMjBzaG93JTIwdGhlYXRlcnxlbnwxfHx8fDE3NjAwNjEzNTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 8.1,
    year: 2024,
    type: 'film' as const,
    description: 'Kveldshow med de morsomste komediantene.',
    duration: 72,
    mood: ['latter', 'kos'],
    genres: ['komedie'],
    language: 'engelsk',
    intensity: 'lett',
    familyFriendly: true
  },
  {
    id: '12',
    title: 'Arctic Expedition',
    platform: 'Discovery+',
    image: 'https://images.unsplash.com/photo-1603016129004-c7539f86b53f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjBkb2N1bWVudGFyeXxlbnwxfHx8fDE3NjAwNDk0Njh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 9.0,
    year: 2024,
    type: 'serie' as const,
    description: 'Dokumentar om livet i Arktis og klimaendringer.',
    duration: 48,
    mood: ['laring', 'kos'],
    genres: ['dokumentar'],
    language: 'engelsk',
    intensity: 'lett',
    familyFriendly: true
  },
];

export const liveChannels = [
  {
    id: 'tv1',
    name: 'NRK1',
    currentShow: 'Dagsrevyen',
    time: '19:00 - 19:45',
  },
  {
    id: 'tv2',
    name: 'TV 2',
    currentShow: 'Skal vi danse',
    time: '20:00 - 21:30',
  },
  {
    id: 'tv3',
    name: 'TVNorge',
    currentShow: 'Praktisk info',
    time: '19:30 - 20:00',
  },
];

export const platformTrends = [
  {
    id: 'trend1',
    platform: 'Netflix',
    icon: 'N',
    color: '#E50914',
    label: 'T-mood trending',
    title: 'The Last Expedition',
    viewers: '2.3M seere i dag',
  },
  {
    id: 'trend2',
    platform: 'Viaplay',
    icon: 'V',
    color: '#1A1A1A',
    label: 'T-mood favoritt',
    title: 'Planet Earth III',
    viewers: '850K seere i dag',
  },
  {
    id: 'trend3',
    platform: 'Disney+',
    icon: 'D',
    color: '#113CCF',
    label: 'Nytt T-mood',
    title: 'Family Adventure',
    viewers: '1.2M seere i dag',
  },
];

export const friendsRecommendations = [
  {
    id: 'rec1',
    friendName: 'Emma Larsen',
    friendAvatar: 'E',
    contentId: '1',
    contentTitle: 'The Last Expedition',
    contentImage: 'https://images.unsplash.com/photo-1739891251370-05b62a54697b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhY3Rpb24lMjBtb3ZpZSUyMHBvc3RlcnxlbnwxfHx8fDE3NjAwNzA2NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    platform: 'Netflix',
    rating: 9.5,
    comment: 'Fantastisk film! Må sees! 🔥',
    category: 'Action',
    isConnected: true
  },
  {
    id: 'rec2',
    friendName: 'Magnus Berg',
    friendAvatar: 'M',
    contentId: '2',
    contentTitle: 'Planet Earth III',
    contentImage: 'https://images.unsplash.com/photo-1603016129004-c7539f86b53f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjBkb2N1bWVudGFyeXxlbnwxfHx8fDE3NjAwNDk0Njh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    platform: 'Viaplay',
    rating: 10,
    comment: 'Utrolig vakre bilder! 🌍',
    category: 'Dokumentar',
    isConnected: true
  },
  {
    id: 'rec3',
    friendName: 'Sofie Hansen',
    friendAvatar: 'S',
    contentId: '6',
    contentTitle: 'Dark Secrets',
    contentImage: 'https://images.unsplash.com/photo-1647264157150-491bfd016aa1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aHJpbGxlciUyMGRhcmslMjBteXN0ZXJ5fGVufDF8fHx8MTc2MDEyMjA2M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    platform: 'Netflix',
    rating: 9.0,
    comment: 'Wow, hvilken slutt! 🤯',
    category: 'Thriller',
    isConnected: true
  },
  {
    id: 'rec4',
    friendName: 'Jonas Nilsen',
    friendAvatar: 'J',
    contentId: '4',
    contentTitle: 'Love in Paris',
    contentImage: 'https://images.unsplash.com/photo-1658851866325-49fb8b7fbcb2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb21hbnRpYyUyMGNvdXBsZSUyMHN1bnNldHxlbnwxfHx8fDE3NjAwODE4MTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    platform: 'Disney+',
    rating: 8.5,
    comment: 'Perfekt kosekveId! 💕',
    category: 'Romantikk',
    isConnected: true
  },
  {
    id: 'rec5',
    friendName: 'Kristine Sørensen',
    friendAvatar: 'K',
    contentId: '',
    contentTitle: '',
    contentImage: '',
    platform: '',
    rating: 0,
    comment: '',
    category: 'Action, Sci-Fi',
    isConnected: false
  },
  {
    id: 'rec6',
    friendName: 'Henrik Johansen',
    friendAvatar: 'H',
    contentId: '',
    contentTitle: '',
    contentImage: '',
    platform: '',
    rating: 0,
    comment: '',
    category: 'Dokumentar, Drama',
    isConnected: false
  },
];

export const friendActivity = [
  {
    id: 'act1',
    friendName: 'Emma Larsen',
    action: 'anbefalte',
    platform: 'Netflix',
    contentTitle: 'The Last Expedition',
    comment: 'Fantastisk film! Må sees!',
    time: '2t siden',
    likes: 12,
    comments: 3,
  },
  {
    id: 'act2',
    friendName: 'Magnus Berg',
    action: 'ser nå',
    platform: 'Viaplay',
    contentTitle: 'Planet Earth III',
    comment: null,
    time: '3t siden',
    likes: 8,
    comments: 1,
  },
  {
    id: 'act3',
    friendName: 'Sofie Hansen',
    action: 'fullførte',
    platform: 'HBO Max',
    contentTitle: 'Dark Secrets',
    comment: 'Wow, hvilken slutt! 🤯',
    time: '5t siden',
    likes: 15,
    comments: 5,
  },
  {
    id: 'act4',
    friendName: 'Jonas Nilsen',
    action: 'anbefalte',
    platform: 'Disney+',
    contentTitle: 'Love in Paris',
    comment: 'Perfekt til en kosekveId!',
    time: '1d siden',
    likes: 20,
    comments: 7,
  },
  {
    id: 'act5',
    friendName: 'Maria Olsen',
    action: 'la til i listen',
    platform: 'Prime Video',
    contentTitle: 'Future World',
    comment: null,
    time: '1d siden',
    likes: 5,
    comments: 0,
  },
];
